---
title: Quiz 2
subtitle: >
  All topics covered in the course so far in a short, open-book quiz
categories: [bash, linux, python, iot]
date: 2025-05-05
---

## Virtual Env Exercises

The following exercises are meant for familiarization with `venv`.


1. Complete the following steps inside a virtual environment

    1. Create a virtual environment
    1. Activate the virt. env.
    1. install the following libraries:
        - [howdoi](https://pypi.org/project/howdoi/)
        - [pyjokes](https://pyjok.es/)
    1. List all pip packages to see the extra dependencies that got installed.
    1. Have some fun using both installed packages (see their docs).
    1. Export the dependency list to `requirements.txt` by using `pip freeze`.
    1. Deactivate the virt. env.
    1. Move `requirements.txt` to one folder level above the project folder (so it's not
        deleted in the next step).
    1. Delete the project folder.

1. Create a new project and virtual environment using the `requirements.txt` from the
    previous exercise.

    1. Create a new project folder with a virtual environment inside.
    1. Move `requirements.txt` inside the new project folder.
    1. Install project packages using `requirements.txt`
