---
title: "Azure Plan Troubleshooting"
date: 2024-04-18
---

{{< include /_reference-links.md >}}

In setting up Azure for Lab 6, a few students have asked me about troubles with the following:

- Eligibility for a student Azure plan
- Student Azure plan expiring
- Signing up for the Free-tier of Azure
- Creating a budget for Azure
- Difficulties creating an Azure IoTHub on the Free-tier plan
- Etc.

[course-notes-announcements]: https://john-abbott-college.github.io/6P3-Notes/announcements/2024-04-18-azure-plan-troubleshooting.qmd

I would like to share my help for those students for the rest of you, just in case there are more of you struggling with setting up Azure.

I will keep the Course Website version of this announcement up to date -- if you are seeing this announcement on Moodle, you can [click here][course-notes-announcements] to get to the up-to-date version of this announcement with the latest change

## Big picture

In the big picture, no matter what your situation is, your Azure plan should have the following properties:

1. No **upfront** costs -- your account should be free to create, and every service/resource you create should be free to create.

2. No **monthly** costs -- your costs should be covered entirely by one of the following:

  - a. your student account credit
  - b. $200 free credit for new non-student account
  - c. pay-as-you-go that is **free per month**, but will charge your credit card **per usage**.

3. A budget alert system that warns you when your usage exceeds >$5 . Even if you are in situation (c), you should not expect to pay more than $5 or $10 -- **please set up an alert system and monitor this. Let me know if your costs ever exceed this amount**. See the [course notes on Azure Account Check][azure-account-check].

## FAQ

> Q: I'm not eligible for a student account?

Student accounts last for 18 months -- if you have taken courses in the past that require an Azure account, and it was more than 18 months since you created that account, your student credits have unfortunately expired. There are other free options in this case.

> Q: I'm not eligible for the $200 free account credit for my non-student account?

The $200 credit is only available if you have not used that email address for an Azure account in the past (and it only lasts for one month).

If you are not elgible for the $200 credit on the email address you have provided, you will either need to:
- use a new email address
- register for a free-tier pay-as-you-go.

> Q: I tried to register for the pay-as-you-go and I'm told it costs $35 per month?

The pay-as-you-go account **should not cost any upfront or monthly charges**. Double check that you do not select options like "tech support plans" or "standard-tier service" -- ALWAYS opt out of any paid options, ALWAYS select free-tier for any choices provided to you by Azure.

> Q: if I'm on free-tier and there's no monthly costs, why do I need to monitor the budget?

The pay-as-you-go account may charge your credit card, only when you *use* the service *beyond the defined free-tier limits*. 

In our class, we will have IoT Hub services that handle communication between your Mobile App from App Dev III, and your reTerminal devices from Connected Objects. **The free-tier limit for the IoTHub is 8000 messages per day** -- I don't think there will be a reason to exceed this, so by default, you may never have to pay any money for this serivce.

However, there may be small charges to your credit card, ONLY IF you exceed the free-tier limits of the services we use. These charges will be small, but it is possible for them to get out-of-hand by accident. To make sure they do not get out of hand by accident, you must set up a Budget for your Resource Group to alert you when charges exceed a certain number. [Please review the course notes about budgets and set up an alert if you have not done so][azure-account-check].

> Q: I have some other question?

Please let me know if you have any questions, or if there's something else that doesn't seem to work. I will update these instructions if there are more troubles you run into that I can share answers for. Again, if you are seeing this on moodle, [click here][course-notes-announcements] to see the latest version of these instructions.
