project:
  type: website
  resources:
    - "files/"

website:
  title: "{{< var course.title >}}"
  image: "assets/art_title_path_only.svg"
  favicon: "assets/favicon_io/favicon.ico"
  site-path: "{{< var site.path >}}"
  site-url: https://john-abbott-college.github.io/6P3-Notes/
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  search:
    location: navbar
    show-item-context: true
    type: textbox
    copy-button: true
    keyboard-shortcut: "ctrl+k"
    collapse-after: 4

  navbar:
    left:
      - text: "{{< iconify simple-icons moodle >}}"
        href: "{{< var site.moodle >}}"
      - sidebar:notes
      - text: "Syllabus"
        href: about/syllabus/index.qmd
      - text: "Calendar"
        href: about/calendar/index.qmd
      - text: "About"
        href: about/this-site/index.qmd
      - text: "{{< iconify fa6-brands github >}}"
        href: "{{< var site.repository >}}"
    logo: "assets/favicon_io/favicon-32x32.png"
    pinned: true

  sidebar:
    - id: notes
      title: "Course Notes"
      style: "docked"
      contents:
        - notes/index.qmd
        - auto: "notes/**/index.qmd"

format:
  html:
    theme:
      light: [journal, assets/css/customizations-light.scss]
      dark: [journal, assets/css/customizations-dark.scss]
    toc: true
    toc-expand: 1
    toc-depth: 4
    toc-title: On this page
    toc-location: left
    number-sections: true
    date-modified: last-modified
    code-copy: true
    highlight-style: gruvbox
    lightbox: true
    reference-location: margin
    title-block-banner: false
    page-layout: article
    license:
      text: >
        CC BY-NC 4.0. ©2022-25 Mauricio Buschinelli & Michael Haaf.
      url: http://creativecommons.org/licenses/by-nc/4.0/
