project:
  type: website

website:
  title: "{{< var course.title >}}"
  image: "assets/art_title_path_only.svg"
  favicon: "assets/favicon_io/favicon.ico"
  site-path: "/6P3-Notes/"
  site-url: "https://john-abbott-college.github.io/6P3-Notes/"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  search:
    show-item-context: true
    type: overlay
    copy-button: true

  page-footer:
    left:
      - text: "{{< var course.title >}}: {{< var course.semester >}}"
    center:
      - text: "About"
        href: about/this-site.qmd
      - text: "License"
        href: about/this-site.qmd#copyright
    right:
      - text: "{{< iconify simple-icons moodle >}}"
        menu: 
          - text: "Section 1 (8h30)"
            href: https://moodle.johnabbott.qc.ca/course/view.php?id=807
          - text: "Section 2 (13h30)"
            href: https://moodle.johnabbott.qc.ca/course/view.php?id=808
      - icon: rss
        href: announcements/index.xml
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/John-Abbott-College/6P3-Notes

  navbar:
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Announcements"
        href: announcements/index.qmd
      - text: "Lectures"
        href: lectures/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "{{< iconify simple-icons moodle >}}"
        menu: 
          - text: "Section 1 (8h30)"
            href: https://moodle.johnabbott.qc.ca/course/view.php?id=807
          - text: "Section 2 (13h30)"
            href: https://moodle.johnabbott.qc.ca/course/view.php?id=808
      - icon: rss
        href: announcements/index.xml
      - text: "{{< iconify fa6-brands github >}}"
        href: https://github.com/John-Abbott-College/6P3-Notes
    logo: "assets/favicon_io/favicon-32x32.png"

format:
  html:
    theme:
      light: [united, assets/css/customizations-light.scss]
      dark: [united, assets/css/customizations-dark.scss]
    toc: true
    toc-depth: 4
    date-modified: last-modified
    code-overflow: wrap
    lightbox: true
    reference-location: margin
