project:
  type: website
  resources:
    - "files/"

website:
  title: "{{< var course.title >}}"
  image: "assets/art_title_path_only.svg"
  favicon: "assets/favicon_io/favicon.ico"
  site-path: "{{< site.path >}}"
  site-url: "{{< site.url >}}"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  search:
    show-item-context: true
    type: overlay
    copy-button: true
    keyboard-shortcut: "ctrl+k"

  page-footer:
    left:
      - text: "{{< iconify simple-icons moodle >}}"
        href: "{{< var site.moodle >}}"
      - text: "{{< iconify fa6-brands github >}}"
        href: "{{< var site.repository >}}"
      - text: "{{< var course.title >}}: {{< var course.semester >}}"
    center:
      - text: "About"
        href: about/this-site.qmd
      - text: "License"
        href: about/this-site.qmd#copyright
    right: |
      © Copyright 2024-2025 Michael Haaf

  navbar:
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Announcements"
        href: announcements/index.qmd
      - text: "Lectures"
        href: lectures/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "{{< iconify simple-icons moodle >}}"
        href: "{{< var site.moodle >}}"
      - text: "{{< iconify fa6-brands github >}}"
        href: "{{< var site.repository >}}"
    logo: "assets/favicon_io/favicon-32x32.png"

format:
  html:
    theme:
      light: [united, assets/css/customizations-light.scss]
      dark: [united, assets/css/customizations-dark.scss]
    toc: true
    toc-depth: 4
    toc-title: Table of contents
    toc-location: left
    date-modified: last-modified
    code-overflow: wrap
    code-copy: true
    lightbox: true
    reference-location: margin
    title-block-banner: true
