project:
  type: website
  resources:
    - "files/"

website:
  title: "{{< var course.title >}}"
  image: "assets/art_title_path_only.svg"
  favicon: "assets/favicon_io/favicon.ico"
  site-path: "{{< var site.path >}}"
  site-url: "{{< var site.url >}}"
  open-graph: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  search:
    location: navbar
    show-item-context: true
    type: textbox
    copy-button: true
    keyboard-shortcut: "ctrl+k"

  body-footer: |
    :::{.footer .nav-footer}
      ©2022-25 [Mauricio Buschinelli](https://github.com/maubuz) & [Michael Haaf](https://github.com/michaelhaaf/), [CC BY-NC 4.0](http://creativecommons.org/licenses/by-nc/4.0/).
      [Link to source]({{< var site.repository >}})
    :::

  navbar:
    left:
      - text: "About"
        href: about/index.qmd
      - text: "Announcements"
        href: announcements/index.qmd
      - text: "Lectures"
        href: lectures/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "{{< iconify simple-icons moodle >}}"
        href: "{{< var site.moodle >}}"
      - text: "{{< iconify fa6-brands github >}}"
        href: "{{< var site.repository >}}"
    logo: "assets/favicon_io/favicon-32x32.png"
    pinned: true

format:
  html:
    theme:
      light: [journal, assets/css/customizations-light.scss]
      dark: [journal, assets/css/customizations-dark.scss]
    toc: true
    toc-depth: 4
    toc-title: On this page
    toc-location: left
    number-sections: true
    date-modified: last-modified
    code-overflow: wrap
    code-copy: true
    lightbox: true
    reference-location: margin
    title-block-banner: true
    page-layout: article
