[project]
name = "6P3-Notes"
version = "0.0.0"
description = "Website repository for Connected Objects course 420-6P3"
authors = [
  { name = "michaelhaaf", email = "michael.haaf@johnabbott.qc.ca" },
  { name = "maubuz", email = "mauricio.buschinelli@johnabbott.qc.ca" },
]
requires-python = ">=3.9"
readme = "README.md"
dependencies = []

[dependency-groups]
format = [
    "mdformat>=0.7.21",
    "mdformat-gfm>=0.4.1",
    "ruff>=0.9.1",
    "pymarkdownlnt>=0.9.26",
    "mdformat-toc>=0.3.0",
    "mdformat-frontmatter>=2.0.8",
    "mdformat-wikilink>=0.2.0",
    "mdformat-web>=0.2.0",
    "mdformat-config>=0.2.1",
    "mdformat-ruff>=0.1.3",
    "mdformat-simple-breaks>=0.0.1",
    "mdformat-tables>=1.0.0",
    "mdformat-shfmt>=0.2.0",
    "mdformat-pyproject>=0.0.2",
    "mdformat-deflist>=0.1.3",
    "mdformat-footnote>=0.1.1",
    "mdformat-mkdocs>=4.1.2",
]
git = [
    "python-semantic-release>=9.16.1",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
format-python = "ruff format ."
lint-python = "ruff check ."
format-markdown = "mdformat ."
lint-markdown = "pymarkdownlnt scan -r ."


[tool.semantic_release]
assets = []
build_command_env = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
allow_zero_version = true
repo_dir = "/home/michael/repositories/6P3-Notes"
no_git_verify = false
tag_format = "v{version}"
version_toml = [
  "pyproject.toml:project.version"
]

[tool.semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release.changelog]
exclude_commit_patterns = []
mode = "init"
insertion_flag = "<!-- version list -->"
template_dir = "templates"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"
output_format = "md"
mask_initial_release = false

[tool.semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = false

[tool.semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "Michael Haaf <michael.haaf@gmail.com>"

[tool.semantic_release.commit_parser_options]
minor_tags = ["year"]
patch_tags = ["feat", "fix", "docs"]
other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
allowed_tags = ["year", "feat", "fix", "docs", "build", "chore", "ci", "style", "refactor", "test"]
default_bump_level = 0

[tool.semantic_release.remote]
name = "origin"
type = "github"
ignore_token_for_push = false
insecure = false
token = { env = "GH_TOKEN" }

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
