name: GitHub Pages Deploy
on:
  push:
    branches: [2026]
env:
  # `BASE_URL` determines the website is served from, including CSS & JS assets
  # You may need to change this to `BASE_URL: ''`
  BASE_URL: ""

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Approach adapted from https://skorski.info/2023/03/25/effective-caching-with-github-actions/
      # Doesn't work yet, will try again later.
      # - name: Prepare apt cache
      #   run: |
      #     mkdir -p .apt/archives/partial
      # - name: Set up apt cache
      #   id: cache_deps
      #   uses: actions/cache@v4
      #   env:
      #     cache-name: cache-dependencies
      #   with:
      #     path: |
      #       .apt
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.github/workflows/*') }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build HTML Assets
        run: uv run myst build --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./_build/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
